{% set name = "build123d" %}
{% set version = "0.9.0" %}
# Package is 3.9. But dependencies (lib3mf) prevent building against lowest
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gumyr/build123d/archive/v{{ version }}.tar.gz
  sha256: 5e4b3fc23665ba6ea1374fe98248abeae774cde1f9a5142329d21076331a3834
  patches:
    - 0001-fix-lib3mf-name-and-versioning-to-enable-building-ve.patch

build:
  noarch: python
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm >=6.2
  run:
    - anytree >=2.8.0,<3
    - ezdxf >1.1.0,<2
    - lib3mf-python =2.3.2
    - numpy
    - ocp >=7.7.0
    - ocpsvg
    - python {{ python_min }}
    - svgpathtools >=1.5.1,<2
    - trianglesolver
    - typing_extensions >=4.6.0,<5


test:
  source_files:
    - tests/
  imports:
    - build123d
  requires:
    - pip
    - python {{ python_min }}
    - libgl    # [linux]
    - pytest
  commands:
    - pip check
    - pytest

about:
  home: https://github.com/gumyr/build123d
  summary: 'A python CAD programming library'
  description: |
    Build123d is a python-based, parametric, boundary representation (BREP)
    modeling framework for 2D and 3D CAD. It's built on the Open Cascade
    geometric kernel and allows for the creation of complex models using a
    simple and intuitive python syntax. Build123d can be used to create
    models for 3D printing, CNC machining, laser cutting, and other
    manufacturing processes. Models can be exported to a wide variety of
    popular CAD tools such as FreeCAD and SolidWorks.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://build123d.readthedocs.io/

extra:
  recipe-maintainers:
    - ndevenish
