{% set name = "build123d" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gumyr/build123d/archive/v{{ version }}.tar.gz
  sha256: 604f33a6518f97d1f59a5b6caa11748c61de00d0dd89177930a72dfbaacee8c4
  patches:
    - 0001-Use-lib3mf-python.patch
    - 0002-Don-t-try-to-help-lib3mf-find-it-s-library.patch
    - 0003-Change-explicit-dependency-lock-version.patch
    - 0004-Fix-raw-regex.patch
    - 0005-Fix-dependency-names-for-conda-forge.patch

build:
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
    - setuptools_scm >=6.2
  run:
    - anytree >=2.8.0,<3
    - cadquery
    - ezdxf >1.1.0,<2
    - lib3mf-python =2.3.2
    - numpy
    - ocp >=7.7.0
    - ocpsvg
    - python >=3.9
    - svgpathtools >=1.5.1,<2
    - trianglesolver
    - typing_extensions >=4.6.0,<5


test:
  source_files:
    - tests/
  imports:
    - build123d
  requires:
    - pip
    - libgl    # [linux]
    - pytest
  commands:
    - pip check
    - pytest

about:
  home: https://github.com/gumyr/build123d
  summary: 'A python CAD programming library'
  description: |
    Build123d is a python-based, parametric, boundary representation (BREP)
    modeling framework for 2D and 3D CAD. It's built on the Open Cascade
    geometric kernel and allows for the creation of complex models using a
    simple and intuitive python syntax. Build123d can be used to create
    models for 3D printing, CNC machining, laser cutting, and other
    manufacturing processes. Models can be exported to a wide variety of
    popular CAD tools such as FreeCAD and SolidWorks.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://build123d.readthedocs.io/

extra:
  recipe-maintainers:
    - ndevenish
